---
- name: Run Ansible Playbook
  hosts: localhost
  tasks:
    - name: Perform some tasks
      debug:
        msg: "Executing tasks..."

    - name: Set custom stats
      set_stats:
        data:
          my_custom_stat: "RAM"

    - name: Save custom stats to a file
      copy:
        content: "{{ ansible_run_stats.my_custom_stat }}"
        dest: "/tmp/custom_stat.txt"
