---
- name: Run Ansible Playbook
  hosts: localhost
  vars:
      my_custom_stat_value: "RAMEN"

  tasks:
    - name: Set custom stat
      set_stats:
        data:
          my_custom_stat: "{{ my_custom_stat_value }}"

    - name: Save Ansible Facts
      copy:
        content: "{{ my_custom_stat }}"
        dest: "/tmp/facts_output.json"

    # - name: Trigger handler to save custom stat to file
    #   meta: flush_handlers

  # handlers:
  #   - name: Save custom stat to file
  #     blockinfile:
  #       path: /tmp/custom_stat.txt
  #       block: "{{ my_custom_stat_value }}"

    # - name: Set custom stats as facts
    #   set_fact:
    #     my_custom_stat: "TREE"

    # - name: Save custom stat to a file
    #   copy:
    #     content: "{{ my_custom_stat }}"
    #     dest: "/tmp/custom_stat.txt"        


