---
    name: Run Workload for Kk Group

    on:
      push:
        branches:
          - main
    
    jobs:
      run-workload:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              path: './git_wif_tst2'

          - name: Check if actor is in Kk group
            run: |
                echo current working directory: $PWD
                file_path="./.github/CODEOWNERS"
                echo ls -la
                
                # Fetch the raw content from GitHub
                content=$(cat ${file_path})
                echo $content
                
                # Process the content line by line
                while IFS= read -r line; do
                    if [[ $line == /dev* && $line == *@* ]]; then
                        # Extract team names starting with @
                        team_names=$(echo "$line" | grep -o '@[a-zA-Z0-9_]*')
                        
                        # Print team names
                        echo "Team names on the line starting with /dev: $team_names"
                    fi
                done <<< "$content"

                # TEAM_NAME="kk"
                # USERNAME="${{ github.actor }}"
                # TOKEN="${{ secrets.TOKEN }}"
    
                # # Get the team ID by name
                # TEAM_ID=$(curl -s -H "Authorization: Bearer $TOKEN" "https://api.github.com/orgs/smallinc/teams/$TEAM_NAME" | jq -r '.id')
                # echo $TEAM_ID
                # # Check if TEAM_ID is null or empty
                # if [ -z "$TEAM_ID" ]; then
                #     echo "Team ID is null. Setting default value."
                #     TEAM_ID="9090732"
                # else
                #     echo "Team ID is: $TEAM_ID"
                # fi
                # # Check if the actor is a member of the team
                # if [ "$(curl -s -H "Authorization: Bearer $TOKEN" "https://api.github.com/teams/$TEAM_ID/memberships/$USERNAME" | jq -r '.state')" == "active" ]; then
                #     echo "User is in Kelo team. Run your workload here."
                # else
                #     echo "User is not in Kelo team. Skipping workload."
                #     exit 0
                # fi  

            shell: bash