---
    name: Conditional Workflow

    on:
      workflow_run:
        workflows: ["your-main-workflow"]
        types:
          - requested
      workflow_dispatch:
        inputs:
          PROJECT_NAME:
            description: 'Project Level'
            required: true
            type: choice
            options: ['dev', 'prd']      
 
        
    

    
      main_workflow:
        needs: check_code_owner
        runs-on: ubuntu-latest
        if: steps.check_owner.outputs.code_owner == 'true'
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
    
          # Your main workflow steps here
