---
    name: Conditional Workflow

    on:
      workflow_run:
        workflows: ["your-main-workflow"]
        types:
          - requested
      workflow_dispatch:
        inputs:
          PROJECT_NAME:
            description: 'Project Level'
            required: true
            type: choice
            options: ['dev', 'prd']      
 
        
    
    jobs:
      check_code_owner:
        runs-on: ubuntu-latest
        steps:
        - name: Check if actor is in Kk \
          id: check_owner
          run: |
            if [ "$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/orgs/smallinc/teams/Kk/members" | jq '.[].login' | grep -w "${{ github.actor }}" )" ]; then
              echo "User is in Kk group. Run your workload here."
            else
              echo "User is not in Kk group. Skipping workload."
              exit 0
            fi
          shell: bash
    
      main_workflow:
        needs: check_code_owner
        runs-on: ubuntu-latest
        if: steps.check_owner.outputs.code_owner == 'true'
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
    
          # Your main workflow steps here