---
name: Run Workload for Kk reuse Group

on:
    # push:
        # branches:
        # - main
    workflow_dispatch:
        inputs:
          PROJECT_NAME:
            description: 'Project Level'
            required: true
            type: choice
            options: ['dev', 'prod']
          RELEASE_BRANCH:
            description: 'Select the service release branch to checkout the code repo'
            required: true
            type: string
            default: "main"
jobs:
    run-workload:
     uses: ./.github/workflows/reusable_wf.yml
     with:
        PROJECT_NAME: ${{ inputs.PROJECT_NAME }}
        RELEASE_BRANCH: ${{ inputs.RELEASE_BRANCH }}
     secrets: 
        GHA_PAT: ${{ secrets.TOKEN }}