name: Status Summary1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    name: Test1
    runs-on: ubuntu-latest
  
    outputs:
      id: output_var
      value: "Default Value"

    steps:
    # Add your build/test steps here
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: './test'

    - name: Install Python and Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install ansible

    - name: Display Ansible version
      run: ansible --version

    - name: Run the playbook
      run: |
          echo current working directory: $PWD
          cd test
          ls -la
          echo ls -la
          cd ansible
          ls -la
          echo ls -la
          ansible-playbook ./playbook/test2_playbook.yml
      shell: bash
      id: set1

    - name: Display custom stat from file
      id: step1
      run: |
        # Read the content of the JSON file
        sudo apt-get install -y jq
        cat /tmp/json_file.json | base64 -d
        json_content=$(/tmp/json_file.json | base64 -d)

        # Parse the JSON content and print the value of the 'name' key
        name_value=$(echo "$json_content" | jq -r .Name1)
        echo "Value of 'name' key: $name_value"


    - name: Set status check - Success
      run: |
        {
          json_content=$(/tmp/json_file.json | base64 -d)

          # Parse the JSON content and print the value of the 'name' key
          output=$(echo "$json_content" | jq -r .Name1)

            echo "### :rocket: Workflow inputs"
            echo "| Arg                 | Value |"
            echo "| ------------------- | ----- |"
            echo "| Print inputs        | $output |"
            echo "| Environment         | Dev|"
            echo "| Cluster             | F22 |"
        } >> $GITHUB_STEP_SUMMARY

      


