name: Status Summary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    name: Test1
    runs-on: ubuntu-latest

    steps:
    # Add your build/test steps here
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: './test'

    - name: Install Python and Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install ansible

    - name: Display Ansible version
      run: ansible --version

    - name: Run the playbook
      run: |
          echo current working directory: $PWD
          cd test
          ls -la
          echo ls -la
          cd ansible
          ls -la
          echo ls -la
          ansible-playbook .\playbook\test_playbook.yml
      shell: bash

    - name: Display custom stat
      run: |
        echo "Custom Stat: ${{ env.ANSIBLE_RUN_STATS_MY_CUSTOM_STAT }}"

    - name: Set status check - Success
      run: |
        {
            echo "### :rocket: Workflow inputs"
            echo "| Arg                 | Value |"
            echo "| ------------------- | ----- |"
            echo "| Print inputs        | Rupesh |"
            echo "| Environment         | Dev|"
            echo "| Cluster             | F22 |"
        } >> $GITHUB_STEP_SUMMARY

      


