name: Status Summary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    name: Test1
    runs-on: ubuntu-latest
  
    outputs:
      id: output_var
      value: "Default Value"

    steps:
    # Add your build/test steps here
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: './test'

    - name: Install Python and Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install ansible

    - name: Display Ansible version
      run: ansible --version

    - name: Run the playbook
      run: |
          echo current working directory: $PWD
          cd test
          ls -la
          echo ls -la
          cd ansible
          ls -la
          echo ls -la
          ansible-playbook ./playbook/test_playbook.yml
          #custom_stat=$(ansible-playbook ./playbook/test_playbook.yml --json|jq -r .stats.hosts.localhost.my_custom_stat)
          #echo "Custom Stat: ${{ env.ANSIBLE_RUN_STATS_MY_CUSTOM_STAT }}"
          #echo "Custom Stat: $custom_stat"
          #echo "::set-output name=custom_stat::$custom_stat"
      shell: bash
      id: set1

    - name: Display custom stat from file
      id: step1
      run: |
        cat /tmp/custom_stat.txt
        output=$(cat /tmp/custom_stat.txt)
        #echo "Output from Step 1: $output"
        echo "test=$output" >> "$GITHUB_OUTPUT"

        # Set the output as an output variable
        echo "::set-output name=output_var::$output"

    # - name: Read custom stat from file
    #   run: echo "::set-output name=custom_stat::$(cat /tmp/custom_stat.txt)"
    #   id: set_custom_stat

    - name: Display Custom Stat
      run: |
        # Access the output variable from the previous step
        previous_output="${{ steps.step1.outputs.output_var }}"
        echo "Output from Step 2 using previous output: $previous_output"

    # - name: Display custom stat
    #   run: |
    #     echo "::set-output name=custom_stat::${{ steps.set1.outputs.custom_stat }}"

    - name: Set status check - Success
      run: |
        {
            cat /tmp/custom_stat.txt
            output=$(cat /tmp/custom_stat.txt)
            echo "### :rocket: Workflow inputs"
            echo "| Arg                 | Value |"
            echo "| ------------------- | ----- |"
            echo "| Print inputs        | $output |"
            echo "| Environment         | Dev|"
            echo "| Cluster             | F22 |"
        } >> $GITHUB_STEP_SUMMARY

      


