name: Status Summary

on:
  workflow_dispatch:
    inputs:
      guid:
        description: 'unique identifier of string type' 
        type: string
      PROJECT_NAME:
        description: 'Project Level'
        required: true
        type: choice
        options: ['dev', 'prod']	

jobs:
  build:
    name: Test1
    runs-on: ubuntu-latest
  
    outputs:
      id: output_var
      value: "Default Value"

    steps:
    # Add your build/test steps here
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: './test'

    - name: Install Python and Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install ansible

    - name: Display Ansible version
      run: ansible --version

    - name: Run the playbook
      run: |
          echo current working directory: $PWD
          cd test
          ls -la
          echo ls -la
          cd ansible
          ls -la
          echo ls -la
          ANSIBLE_SHOW_CUSTOM_STATS=true ansible-playbook ./playbook/test_playbook.yml
      shell: bash
      id: set1

    - name: Display custom stat from file
      id: step1
      run: |
        cat /tmp/custom_stat.txt
        output=$(cat /tmp/custom_stat.txt)
        #echo "Output from Step 1: $output"
        echo "test=$output" >> "$GITHUB_OUTPUT"

        # Set the output as an output variable
        echo "::set-output name=output_var::$output"

    # - name: Read custom stat from file
    #   run: echo "::set-output name=custom_stat::$(cat /tmp/custom_stat.txt)"
    #   id: set_custom_stat

    - name: Display Custom Stat
      run: |
        # Access the output variable from the previous step
        previous_output="${{ steps.step1.outputs.test }}"
        echo "Output from Step 2 using previous output: $previous_output"

    # - name: Display custom stat
    #   run: |
    #     echo "::set-output name=custom_stat::${{ steps.set1.outputs.custom_stat }}"

    - name: Set status check - Success
      run: |
        {
            # cat /tmp/custom_stat.txt
            # output=$(cat /tmp/custom_stat.txt)
            # echo "### :book: *Workflow inputs*"
            # echo "| Arg                 | Value |"
            # echo "| :-------------------: | :-----: |"
            # echo "| Print inputs        | '${{ inputs.guid }}' |"
            # echo "| Environment         | '${{ inputs.PROJECT_NAME }}'|"
            # echo "| Cluster             | F22 |"

            # echo -e "# $underlined_text #"
            # echo -e "<u>Paraphase</u>"
            # echo "### :star: _*Workflow outputs*_"
            # echo "| Arg                 | Value |"
            # echo "| :------------------- | :----- |"
            # echo "| Print inputs        | $output |"
            # echo "| Environment         | Dev|"
            # echo "| Cluster             | F22 |"
            table1="| Table 1 |      |      |
            |---------|------|------|
            | Row 1   |      |      |
            | Row 2   |      |      |"

            table2="| Table 2 |      |      |
            |---------|------|------|
            | Row 1   |      |      |
            | Row 2   |      |      |"

            echo "<div style=\"display: inline-block;\">"
            echo "$table1"
            echo "</div>"

            echo "<div style=\"display: inline-block;\">"
            echo "$table2"
            echo "</div>"
        } >> $GITHUB_STEP_SUMMARY

      


