name: Status Summary1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    name: Test1
    runs-on: ubuntu-latest
  
    outputs:
      id: output_var
      value: "Default Value"

    steps:
    # Add your build/test steps here
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: './test'

    - name: Install Python and Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install ansible

    - name: Display Ansible version
      run: ansible --version

    - name: Run the playbook
      run: |
          echo current working directory: $PWD
          cd test
          ls -la
          echo ls -la
          cd ansible
          ls -la
          echo ls -la
          ansible-playbook ./playbook/test2_playbook.yml
          #custom_stat=$(ansible-playbook ./playbook/test_playbook.yml --json|jq -r .stats.hosts.localhost.my_custom_stat)
          #echo "Custom Stat: ${{ env.ANSIBLE_RUN_STATS_MY_CUSTOM_STAT }}"
          #echo "Custom Stat: $custom_stat"
          #echo "::set-output name=custom_stat::$custom_stat"
      shell: bash
      id: set1

    - name: Display custom stat from file
      id: step1
      run: |
        # Read the content of the JSON file
        json_content=$(cat /tmp/json_file.json)

        # Parse the JSON content and print the value of the 'name' key
        name_value=$(echo "$json_content" | jq -r .name)
        echo "Value of 'name' key: $name_value"


    - name: Set status check - Success
      run: |
        {
          json_content=$(cat /tmp/json_file.json)

          # Parse the JSON content and print the value of the 'name' key
          output=$(echo "$json_content" | jq -r .name)
            output=$(cat /tmp/custom_stat.txt)
            echo "### :rocket: Workflow inputs"
            echo "| Arg                 | Value |"
            echo "| ------------------- | ----- |"
            echo "| Print inputs        | $output |"
            echo "| Environment         | Dev|"
            echo "| Cluster             | F22 |"
        } >> $GITHUB_STEP_SUMMARY

      


